/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servlet_;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author ASUS
 */
@WebServlet(name = "formAddMinatBakat_suster", urlPatterns = {"/formAddMinatBakat_suster"})
public class formAddMinatBakat_suster extends HttpServlet {

    /**
     * Processes requests for both HTTP <code>GET</code> and <code>POST</code>
     * methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        PrintWriter out = response.getWriter();

        out.println("<html>\n"
                + "        <head>\n"
                + "            <meta charset=\"UTF-8\">\n"
                + "            <title>ADD MINAT BAKAT SUSTER</title>\n"
                + "            <link rel=\"stylesheet\" href=\"https://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.css\">\n"
                + "            <link href='https://fonts.googleapis.com/css?family=Lato:300,400' rel='stylesheet' type='text/css'><link rel=\"stylesheet\" href=\"#\">\n"
                + "            <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css\">\n"
                + "            <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js\"></script>\n"
                + "            <script src=\"https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js\"></script>\n"
                + "            <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js\"></script>\n"
                + "            <style type=\"text/css\">\n"
                + "                html, body, div, span, applet, object, iframe,\n"
                + "                h1, h2, h3, h4, h5, h6, p, blockquote, pre,\n"
                + "                a, abbr, acronym, address, big, cite, code,\n"
                + "                del, dfn, em, img, ins, kbd, q, s, samp,\n"
                + "                small, strike, strong, sub, sup, tt, var,\n"
                + "                b, u, i, center,\n"
                + "                dl, dt, dd, ol, ul, li,\n"
                + "                fieldset, form, label, legend,\n"
                + "                table, caption, tbody, tfoot, thead, tr, th, td,\n"
                + "                article, aside, canvas, details, embed,\n"
                + "                figure, figcaption, footer, header, hgroup,\n"
                + "                menu, nav, output, ruby, section, summary,\n"
                + "                time, mark, audio, video {\n"
                + "                    margin: 0;\n"
                + "                    padding: 0;\n"
                + "                    border: 0;\n"
                + "                    font: inherit;\n"
                + "                    font-size: 100%;\n"
                + "                    vertical-align: baseline;\n"
                + "                }\n"
                + "\n"
                + "                html {\n"
                + "                    line-height: 1;\n"
                + "                }\n"
                + "\n"
                + "                ol, ul {\n"
                + "                    list-style: none;\n"
                + "                }\n"
                + "\n"
                + "                table {\n"
                + "                    border-collapse: collapse;\n"
                + "                    border-spacing: 0;\n"
                + "                }\n"
                + "\n"
                + "                caption, th, td {\n"
                + "                    text-align: left;\n"
                + "                    font-weight: normal;\n"
                + "                    vertical-align: middle;\n"
                + "                }\n"
                + "\n"
                + "                q, blockquote {\n"
                + "                    quotes: none;\n"
                + "                }\n"
                + "                q:before, q:after, blockquote:before, blockquote:after {\n"
                + "                    content: \"\";\n"
                + "                    content: none;\n"
                + "                }\n"
                + "\n"
                + "                a img {\n"
                + "                    border: none;\n"
                + "                }\n"
                + "\n"
                + "                article, aside, details, figcaption, figure, footer, header, hgroup, main, menu, nav, section, summary {\n"
                + "                    display: block;\n"
                + "                }\n"
                + "\n"
                + "                /* Colors */\n"
                + "                /* ---------------------------------------- */\n"
                + "                * {\n"
                + "                    -moz-box-sizing: border-box;\n"
                + "                    -webkit-box-sizing: border-box;\n"
                + "                    box-sizing: border-box;\n"
                + "                }\n"
                + "\n"
                + "                body {\n"
                + "                    text-align: center;\n"
                + "                    font-family: 'Lato', 'sans-serif';\n"
                + "                    font-weight: 400;\n"
                + "                }\n"
                + "\n"
                + "                a {\n"
                + "                    text-decoration: none;\n"
                + "                }\n"
                + "\n"
                + "                .info-text {\n"
                + "                    text-align: left;\n"
                + "                    width: 100%;\n"
                + "                }\n"
                + "\n"
                + "                header, form {\n"
                + "                    padding: 4em 10%;\n"
                + "                }\n"
                + "\n"
                + "                .form-group {\n"
                + "                    margin-bottom: 20px;\n"
                + "                }\n"
                + "\n"
                + "                h2.heading {\n"
                + "                    font-size: 18px;\n"
                + "                    text-transform: uppercase;\n"
                + "                    font-weight: 300;\n"
                + "                    text-align: left;\n"
                + "                    color: #506982;\n"
                + "                    border-bottom: 1px solid #506982;\n"
                + "                    padding-bottom: 3px;\n"
                + "                    margin-bottom: 20px;\n"
                + "                }\n"
                + "\n"
                + "                .controls {\n"
                + "                    text-align: left;\n"
                + "                    position: relative;\n"
                + "                }\n"
                + "                .controls input[type=\"text\"],\n"
                + "                .controls input[type=\"email\"],\n"
                + "                .controls input[type=\"number\"],\n"
                + "                .controls input[type=\"date\"],\n"
                + "                .controls input[type=\"tel\"],\n"
                + "                .controls textarea,\n"
                + "                .controls button,\n"
                + "                .controls select {\n"
                + "                    padding: 12px;\n"
                + "                    font-size: 14px;\n"
                + "                    border: 1px solid #c6c6c6;\n"
                + "                    width: 100%;\n"
                + "                    margin-bottom: 18px;\n"
                + "                    color: #888;\n"
                + "                    font-family: 'Lato', 'sans-serif';\n"
                + "                    font-size: 16px;\n"
                + "                    font-weight: 300;\n"
                + "                    -moz-border-radius: 2px;\n"
                + "                    -webkit-border-radius: 2px;\n"
                + "                    border-radius: 2px;\n"
                + "                    -moz-transition: all 0.3s;\n"
                + "                    -o-transition: all 0.3s;\n"
                + "                    -webkit-transition: all 0.3s;\n"
                + "                    transition: all 0.3s;\n"
                + "                }\n"
                + "                .controls input[type=\"text\"]:focus, .controls input[type=\"text\"]:hover,\n"
                + "                .controls input[type=\"email\"]:focus,\n"
                + "                .controls input[type=\"email\"]:hover,\n"
                + "                .controls input[type=\"number\"]:focus,\n"
                + "                .controls input[type=\"number\"]:hover,\n"
                + "                .controls input[type=\"date\"]:focus,\n"
                + "                .controls input[type=\"date\"]:hover,\n"
                + "                .controls input[type=\"tel\"]:focus,\n"
                + "                .controls input[type=\"tel\"]:hover,\n"
                + "                .controls textarea:focus,\n"
                + "                .controls textarea:hover,\n"
                + "                .controls button:focus,\n"
                + "                .controls button:hover,\n"
                + "                .controls select:focus,\n"
                + "                .controls select:hover {\n"
                + "                    outline: none;\n"
                + "                    border-color: #9FB1C1;\n"
                + "                }\n"
                + "                .controls input[type=\"text\"]:focus + label, .controls input[type=\"text\"]:hover + label,\n"
                + "                .controls input[type=\"email\"]:focus + label,\n"
                + "                .controls input[type=\"email\"]:hover + label,\n"
                + "                .controls input[type=\"number\"]:focus + label,\n"
                + "                .controls input[type=\"number\"]:hover + label,\n"
                + "                .controls input[type=\"date\"]:focus + label,\n"
                + "                .controls input[type=\"date\"]:hover + label,\n"
                + "                .controls input[type=\"tel\"]:focus + label,\n"
                + "                .controls input[type=\"tel\"]:hover + label,\n"
                + "                .controls textarea:focus + label,\n"
                + "                .controls textarea:hover + label,\n"
                + "                .controls button:focus + label,\n"
                + "                .controls button:hover + label,\n"
                + "                .controls select:focus + label,\n"
                + "                .controls select:hover + label {\n"
                + "                    color: #bdcc00;\n"
                + "                    cursor: text;\n"
                + "                }\n"
                + "                .controls .fa-sort {\n"
                + "                    position: absolute;\n"
                + "                    right: 10px;\n"
                + "                    top: 17px;\n"
                + "                    color: #999;\n"
                + "                }\n"
                + "                .controls select {\n"
                + "                    -moz-appearance: none;\n"
                + "                    -webkit-appearance: none;\n"
                + "                    cursor: pointer;\n"
                + "                }\n"
                + "                .controls label {\n"
                + "                    position: absolute;\n"
                + "                    left: 8px;\n"
                + "                    top: 12px;\n"
                + "                    width: 60%;\n"
                + "                    color: #999;\n"
                + "                    font-size: 16px;\n"
                + "                    display: inline-block;\n"
                + "                    padding: 4px 10px;\n"
                + "                    font-weight: 400;\n"
                + "                    background-color: rgba(255, 255, 255, 0);\n"
                + "                    -moz-transition: color 0.3s, top 0.3s, background-color 0.8s;\n"
                + "                    -o-transition: color 0.3s, top 0.3s, background-color 0.8s;\n"
                + "                    -webkit-transition: color 0.3s, top 0.3s, background-color 0.8s;\n"
                + "                    transition: color 0.3s, top 0.3s, background-color 0.8s;\n"
                + "                    background-color: white;\n"
                + "                }\n"
                + "                .controls label.active {\n"
                + "                    top: -11px;\n"
                + "                    color: #555;\n"
                + "                    background-color: white;\n"
                + "                    width: auto;\n"
                + "                }\n"
                + "                .controls textarea {\n"
                + "                    resize: none;\n"
                + "                    height: 200px;\n"
                + "                }\n"
                + "\n"
                + "                button {\n"
                + "                    cursor: pointer;\n"
                + "                    background-color: #1b3d4d;\n"
                + "                    border: none;\n"
                + "                    color: #fff;\n"
                + "                    padding: 12px 0;\n"
                + "                    float: right;\n"
                + "                }\n"
                + "                button:hover {\n"
                + "                    background-color: #224c60;\n"
                + "                }\n"
                + "\n"
                + "                .clear:after {\n"
                + "                    content: \"\";\n"
                + "                    display: table;\n"
                + "                    clear: both;\n"
                + "                }\n"
                + "\n"
                + "                .grid {\n"
                + "                    background: white;\n"
                + "                }\n"
                + "                .grid:after {\n"
                + "                    /* Or @extend clearfix */\n"
                + "                    content: \"\";\n"
                + "                    display: table;\n"
                + "                    clear: both;\n"
                + "                }\n"
                + "\n"
                + "                [class*='col-'] {\n"
                + "                    float: left;\n"
                + "                    padding-right: 10px;\n"
                + "                }\n"
                + "                .grid [class*='col-']:last-of-type {\n"
                + "                    padding-right: 0;\n"
                + "                }\n"
                + "\n"
                + "                .col-2-3 {\n"
                + "                    width: 66.66%;\n"
                + "                }\n"
                + "\n"
                + "                .col-1-3 {\n"
                + "                    width: 33.33%;\n"
                + "                }\n"
                + "\n"
                + "                .col-1-2 {\n"
                + "                    width: 50%;\n"
                + "                }\n"
                + "\n"
                + "                .col-1-4 {\n"
                + "                    width: 25%;\n"
                + "                }\n"
                + "\n"
                + "                @media (max-width: 760px) {\n"
                + "                    .col-1-4-sm, .col-1-3, .col-2-3 {\n"
                + "                        width: 100%;\n"
                + "                    }\n"
                + "\n"
                + "                    [class*='col-'] {\n"
                + "                        padding-right: 0px;\n"
                + "                    }\n"
                + "                }\n"
                + "                .col-1-8 {\n"
                + "                    width: 12.5%;\n"
                + "                }\n"
                + "\n"
                + "            </style>\n"
                + "        </head>\n"
                + "        <body>\n"
                + "            \n"
                + "\n"
                + "            <form method=\"POST\" action=\"/projectSusteranADM/tambahSuster_\" enctype=\"multipart/form-data\">\n"
                + "                <!--  General -->\n"
                + "                <div class=\"form-group\">\n"
                + "                    <h2 class=\"heading\"><b>MINAT DAN BAKAT</b></h2>\n"
                + "                    <div class=\"controls\">\n"
                + "                        <input type=\"text\" id=\"idSuster\" class=\"floatLabel\" name=\"idSuster\" value=\"\" maxlength=\"17\" readonly>\n"
                + "                        <label for=\"idSuster\">NIK Suster</label>\n"
                + "                    </div>\n"
                + "                    <div class=\"field_wrapper\">\n"
                + "                        <div>\n"
                + "                            <input type=\"text\" name=\"minatbakat[]\" value=\"\" size=\"30\"/>\n"
                + "                            <a href=\"javascript:void(0);\" class=\"add_button\" title=\"Add field\"><img src=\"https://img.icons8.com/pastel-glyph/64/000000/plus.png\" width=\"25\" height=\"25\"></a>\n"
                + "                        </div>\n"
                + "                    </div>\n"
                + "\n"
                + "                    <div class=\"grid\">\n"
                + "                        <button type=\"submit\" value=\"Submit\" class=\"col-1-4\">SELANJUTNYA</button>\n"
                + "                    </div>\n"
                + "                </div> <!-- /.form-group -->\n"
                + "\n"
                + "            </form>\n"
                + "            <!-- partial -->\n"
                + "            <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>\n"
                + "            <script src='http://raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery-ui-autocomplete.js'></script>\n"
                + "            <script src='http://raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery.select-to-autocomplete.js'></script>\n"
                + "            <script src='http://raw.githubusercontent.com/andiio/selectToAutocomplete/master/jquery.select-to-autocomplete.min.js'></script>\n"
                + "            <script>\n"
                + "                (function ($) {\n"
                + "                    function floatLabel(inputType) {\n"
                + "                        $(inputType).each(function () {\n"
                + "                            var $this = $(this);\n"
                + "                            // on focus add cladd active to label\n"
                + "                            $this.focus(function () {\n"
                + "                                $this.next().addClass(\"active\");\n"
                + "                            });\n"
                + "                            //on blur check field and remove class if needed\n"
                + "                            $this.blur(function () {\n"
                + "                                if ($this.val() === '' || $this.val() === 'blank') {\n"
                + "                                    $this.next().removeClass();\n"
                + "                                }\n"
                + "                            });\n"
                + "                        });\n"
                + "                    }\n"
                + "                    // just add a class of \"floatLabel to the input field!\"\n"
                + "                    floatLabel(\".floatLabel\");\n"
                + "                })(jQuery);\n"
                + "            </script>\n"
                + "            <script>\n"
                + "                // Add the following code if you want the name of the file appear on select\n"
                + "                $(\".custom-file-input\").on(\"change\", function () {\n"
                + "                    var fileName = $(this).val().split(\"\\\\\").pop();\n"
                + "                    $(this).siblings(\".custom-file-label\").addClass(\"selected\").html(fileName);\n"
                + "                });\n"
                + "            </script>\n"
                + "            <script type=\"text/javascript\">\n"
                + "                $(document).ready(function () {\n"
                + "                    var maxField = 10; //Input fields increment limitation\n"
                + "                    var addButton = $('.add_button'); //Add button selector\n"
                + "                    var wrapper = $('.field_wrapper'); //Input field wrapper <img src=\"https://img.icons8.com/flat_round/64/000000/minus.png\">\n"
                + "                    var fieldHTML = '<div><input type=\"text\" name=\"minatbakat[]\" value=\"\" size=\"30\"/><a href=\"javascript:void(0);\" class=\"remove_button\"><img src=\"https://img.icons8.com/pastel-glyph/64/000000/minus.png\" width=\"25\" height=\"25\"></a></div>'; //New input field html \n"
                + "                    var x = 1; //Initial field counter is 1\n"
                + "\n"
                + "                    //Once add button is clicked\n"
                + "                    $(addButton).click(function () {\n"
                + "                        //Check maximum number of input fields\n"
                + "                        if (x < maxField) {\n"
                + "                            x++; //Increment field counter\n"
                + "                            $(wrapper).append(fieldHTML); //Add field html\n"
                + "                        }\n"
                + "                    });\n"
                + "\n"
                + "                    //Once remove button is clicked\n"
                + "                    $(wrapper).on('click', '.remove_button', function (e) {\n"
                + "                        e.preventDefault();\n"
                + "                        $(this).parent('div').remove(); //Remove field html\n"
                + "                        x--; //Decrement field counter\n"
                + "                    });\n"
                + "                });\n"
                + "            </script>\n"
                + "\n"
                + "        </body>\n"
                + "    </html>");

    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {

    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
