/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package servlet_;

import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author ASUS
 */
@WebServlet(name = "ganti_fotoSuster", urlPatterns = {"/ganti_fotoSuster"})
public class ganti_fotoSuster extends HttpServlet {

    /**
     * Handles the HTTP <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        PrintWriter out = response.getWriter();
        String idSuster = request.getParameter("id_suster");
        out.println("                <html lang=\"en\" >\n"
                + "    <head>\n"
                + "        <meta charset=\"UTF-8\">\n"
                + "        <title>Admin Panel</title>\n"
                + "        <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css\">\n"
                + "        <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css'>\n"
                + "        <script src=\"//maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js\"></script>\n"
                + "        <script src=\"//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js\"></script>\n"
                + "        <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js\"></script>\n"
                + "        <style type=\"text/css\">\n"
                + "            @import \"https://designmodo.github.io/Flat-UI/dist/css/flat-ui.min.css\";\n"
                + "            @import \"https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css\";\n"
                + "            @import \"https://daneden.github.io/animate.css/animate.min.css\";\n"
                + "            /*-------------------------------*/\n"
                + "            /*           VARIABLES           */\n"
                + "            /*-------------------------------*/\n"
                + "            body {\n"
                + "                position: relative;\n"
                + "                overflow-x: hidden;\n"
                + "            }\n"
                + "            body,\n"
                + "            html {\n"
                + "                height: 100%;\n"
                + "                background-color: white;\n"
                + "            }\n"
                + "            .nav .open > a {\n"
                + "                background-color: transparent;\n"
                + "            }\n"
                + "            .nav .open > a:hover {\n"
                + "                background-color: transparent;\n"
                + "            }\n"
                + "            .nav .open > a:focus {\n"
                + "                background-color: transparent;\n"
                + "            }\n"
                + "            /*-------------------------------*/\n"
                + "            /*           Wrappers            */\n"
                + "            /*-------------------------------*/\n"
                + "            #wrapper {\n"
                + "                -moz-transition: all 0.5s ease;\n"
                + "                -o-transition: all 0.5s ease;\n"
                + "                -webkit-transition: all 0.5s ease;\n"
                + "                padding-left: 0;\n"
                + "                transition: all 0.5s ease;\n"
                + "            }\n"
                + "            #wrapper.toggled {\n"
                + "                padding-left: 220px;\n"
                + "            }\n"
                + "            #wrapper.toggled #sidebar-wrapper {\n"
                + "                width: 220px;\n"
                + "            }\n"
                + "            #wrapper.toggled #page-content-wrapper {\n"
                + "                margin-right: -220px;\n"
                + "                position: absolute;\n"
                + "            }\n"
                + "            #sidebar-wrapper {\n"
                + "                -moz-transition: all 0.5s ease;\n"
                + "                -o-transition: all 0.5s ease;\n"
                + "                -webkit-transition: all 0.5s ease;\n"
                + "                background: #1a1a1a;\n"
                + "                height: 100%;\n"
                + "                left: 220px;\n"
                + "                margin-left: -220px;\n"
                + "                overflow-x: hidden;\n"
                + "                overflow-y: auto;\n"
                + "                transition: all 0.5s ease;\n"
                + "                width: 0;\n"
                + "                z-index: 1000;\n"
                + "            }\n"
                + "            #sidebar-wrapper::-webkit-scrollbar {\n"
                + "                display: none;\n"
                + "            }\n"
                + "            #page-content-wrapper {\n"
                + "                padding-top: 70px;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            /*-------------------------------*/\n"
                + "            /*     Sidebar nav styles        */\n"
                + "            /*-------------------------------*/\n"
                + "            .sidebar-nav {\n"
                + "                list-style: none;\n"
                + "                margin: 0;\n"
                + "                padding: 0;\n"
                + "                position: absolute;\n"
                + "                top: 0;\n"
                + "                width: 220px;\n"
                + "            }\n"
                + "            .sidebar-nav li {\n"
                + "                display: inline-block;\n"
                + "                line-height: 20px;\n"
                + "                position: relative;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            .sidebar-nav li:before {\n"
                + "                background-color: #F2849E;\n"
                + "                content: '';\n"
                + "                height: 100%;\n"
                + "                left: 0;\n"
                + "                position: absolute;\n"
                + "                top: 0;\n"
                + "                transition: width 0.2s ease-in;\n"
                + "                width: 3px;\n"
                + "                z-index: -1;\n"
                + "            }\n"
                + "            .sidebar-nav li:first-child a {\n"
                + "                background-color: #F2849E;\n"
                + "                color: #ffffff;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(2):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(3):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(4):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(5):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(6):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(7):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(8):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:nth-child(9):before {\n"
                + "                background-color: #F2849E;\n"
                + "            }\n"
                + "            .sidebar-nav li:hover:before {\n"
                + "                transition: width 0.2s ease-in;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            .sidebar-nav li a {\n"
                + "                color: #dddddd;\n"
                + "                display: block;\n"
                + "                padding: 10px 15px 10px 30px;\n"
                + "                text-decoration: none;\n"
                + "            }\n"
                + "            .sidebar-nav li.open:hover before {\n"
                + "                transition: width 0.2s ease-in;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            .sidebar-nav .dropdown-menu {\n"
                + "                background-color: #683E48;\n"
                + "                border-radius: 0;\n"
                + "                border: none;\n"
                + "                box-shadow: none;\n"
                + "                margin: 0;\n"
                + "                padding: 0;\n"
                + "                position: relative;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            .sidebar-nav li a:hover,\n"
                + "            .sidebar-nav li a:active,\n"
                + "            .sidebar-nav li a:focus,\n"
                + "            .sidebar-nav li.open a:hover,\n"
                + "            .sidebar-nav li.open a:active,\n"
                + "            .sidebar-nav li.open a:focus {\n"
                + "                background-color: transparent;\n"
                + "                color: #ffffff;\n"
                + "                text-decoration: none;\n"
                + "            }\n"
                + "            .sidebar-nav > .sidebar-brand {\n"
                + "                font-size: 20px;\n"
                + "                height: 65px;\n"
                + "                line-height: 44px;\n"
                + "            }\n"
                + "            /*-------------------------------*/\n"
                + "            /*       Hamburger-Cross         */\n"
                + "            /*-------------------------------*/\n"
                + "            .hamburger {\n"
                + "                background: transparent;\n"
                + "                border: none;\n"
                + "                display: block;\n"
                + "                height: 32px;\n"
                + "                margin-left: 15px;\n"
                + "                position: fixed;\n"
                + "                top: 20px;\n"
                + "                width: 32px;\n"
                + "                z-index: 999;\n"
                + "            }\n"
                + "            .hamburger:hover {\n"
                + "                outline: none;\n"
                + "            }\n"
                + "            .hamburger:focus {\n"
                + "                outline: none;\n"
                + "            }\n"
                + "            .hamburger:active {\n"
                + "                outline: none;\n"
                + "            }\n"
                + "            .hamburger.is-closed:before {\n"
                + "                -webkit-transform: translate3d(0, 0, 0);\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                color: #ffffff;\n"
                + "                content: '';\n"
                + "                display: block;\n"
                + "                font-size: 14px;\n"
                + "                line-height: 32px;\n"
                + "                opacity: 0;\n"
                + "                text-align: center;\n"
                + "                width: 100px;\n"
                + "            }\n"
                + "            .hamburger.is-closed:hover before {\n"
                + "                -webkit-transform: translate3d(-100px, 0, 0);\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                display: block;\n"
                + "                opacity: 1;\n"
                + "            }\n"
                + "            .hamburger.is-closed:hover .hamb-top {\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                top: 0;\n"
                + "            }\n"
                + "            .hamburger.is-closed:hover .hamb-bottom {\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                bottom: 0;\n"
                + "            }\n"
                + "            .hamburger.is-closed .hamb-top {\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                background-color: rgba(255, 255, 255, 0.7);\n"
                + "                top: 5px;\n"
                + "            }\n"
                + "            .hamburger.is-closed .hamb-middle {\n"
                + "                background-color: rgba(255, 255, 255, 0.7);\n"
                + "                margin-top: -2px;\n"
                + "                top: 50%;\n"
                + "            }\n"
                + "            .hamburger.is-closed .hamb-bottom {\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                background-color: rgba(255, 255, 255, 0.7);\n"
                + "                bottom: 5px;\n"
                + "            }\n"
                + "            .hamburger.is-closed .hamb-top,\n"
                + "            .hamburger.is-closed .hamb-middle,\n"
                + "            .hamburger.is-closed .hamb-bottom,\n"
                + "            .hamburger.is-open .hamb-top,\n"
                + "            .hamburger.is-open .hamb-middle,\n"
                + "            .hamburger.is-open .hamb-bottom {\n"
                + "                height: 4px;\n"
                + "                left: 0;\n"
                + "                position: absolute;\n"
                + "                width: 100%;\n"
                + "            }\n"
                + "            .hamburger.is-open .hamb-top {\n"
                + "                -webkit-transform: rotate(45deg);\n"
                + "                -webkit-transition: -webkit-transform 0.2s cubic-bezier(0.73, 1, 0.28, 0.08);\n"
                + "                background-color: #fff;\n"
                + "                margin-top: -2px;\n"
                + "                top: 50%;\n"
                + "            }\n"
                + "            .hamburger.is-open .hamb-middle {\n"
                + "                background-color: #fff;\n"
                + "                display: none;\n"
                + "            }\n"
                + "            .hamburger.is-open .hamb-bottom {\n"
                + "                -webkit-transform: rotate(-45deg);\n"
                + "                -webkit-transition: -webkit-transform 0.2s cubic-bezier(0.73, 1, 0.28, 0.08);\n"
                + "                background-color: #fff;\n"
                + "                margin-top: -2px;\n"
                + "                top: 50%;\n"
                + "            }\n"
                + "            .hamburger.is-open:before {\n"
                + "                -webkit-transform: translate3d(0, 0, 0);\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                color: #ffffff;\n"
                + "                content: '';\n"
                + "                display: block;\n"
                + "                font-size: 14px;\n"
                + "                line-height: 32px;\n"
                + "                opacity: 0;\n"
                + "                text-align: center;\n"
                + "                width: 100px;\n"
                + "            }\n"
                + "            .hamburger.is-open:hover before {\n"
                + "                -webkit-transform: translate3d(-100px, 0, 0);\n"
                + "                -webkit-transition: all 0.35s ease-in-out;\n"
                + "                display: block;\n"
                + "                opacity: 1;\n"
                + "            }\n"
                + "            /*-------------------------------*/\n"
                + "            /*          Dark Overlay         */\n"
                + "            /*-------------------------------*/\n"
                + "            .overlay {\n"
                + "                position: fixed;\n"
                + "                display: none;\n"
                + "                width: 100%;\n"
                + "                height: 100%;\n"
                + "                top: 0;\n"
                + "                left: 0;\n"
                + "                right: 0;\n"
                + "                bottom: 0;\n"
                + "                background-color: rgba(0, 0, 0, 0.4);\n"
                + "                z-index: 1;\n"
                + "            }\n"
                + "            /* SOME DEMO STYLES - NOT REQUIRED */\n"
                + "            body,\n"
                + "            html {\n"
                + "                background-color: #847676;\n"
                + "            }\n"
                + "            body h1,\n"
                + "            body h2,\n"
                + "            body h3,\n"
                + "            body h4 {\n"
                + "                color: rgba(255, 255, 255, 0.9);\n"
                + "            }\n"
                + "            body p,\n"
                + "            body blockquote {\n"
                + "                color: rgba(255, 255, 255, 0.7);\n"
                + "            }\n"
                + "            body a {\n"
                + "                color: rgba(255, 255, 255, 0.8);\n"
                + "                text-decoration: underline;\n"
                + "            }\n"
                + "            body a:hover {\n"
                + "                color: #fff;\n"
                + "            }\n"
                + "        </style>"
                + "</head>"
                + "<body>"
                + "<form class=\"form\" enctype=\"multipart/form-data\" action=\"./ganti_fotoSuster_save\" method=\"POST\" id=\"registrationForm\">\n"
                + "                                <div class=\"col-xs-6\">\n"
                + "                                    <h4>Foto Suster</h4>\n"
                + "                                    <img src=\"./getImagefromDB?id_suster=" + idSuster + "\" width=\"220\" height=\"130\"/>\n"
                + "                                    <input type=\"file\" class=\"custom-file-input\" id=\"foto_new\" name=\"foto_new\" required accept=\"image/*\"/>\n"
                + "                                    <input type=\"hidden\" class=\"form-control\" name=\"idSuster\" id=\"judul_berita\" value=\"" + idSuster + "\">\n"
                + "                                </div>\n"
                + "<div class=\"form-group\">\n"
                + "                                <div class=\"col-xs-12\">\n"
                + "                                    <br>\n"
                + "                                    <button class=\"button icon solid\" type=\"submit\"><i class=\"glyphicon glyphicon-open\"></i>Terapkan</button>\n"
                + "                                </div>\n"
                + "                            </div>\n"
                + "                        </form>\n"
                + "</body></html>");
    }

    /**
     * Handles the HTTP <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>

}
